__3.2 活性化関数__

In [3]:
#p45
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

In [1]:
import numpy as np

In [4]:
step_function(np.array([1.0,2.0]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [5]:
#p46
import numpy as np
x = np.array([-1.0,2.0])
x

array([-1.,  2.])

In [6]:
y = x > 0
y

array([False,  True])

In [7]:
y = y.astype(np.int)
y

array([0, 1])

In [8]:
def step_function(x):
    y = x > 0
    return y.astype(np.int)