In [4]:
import numpy as np
import matplotlib.pylab as plt

In [5]:
def meanSquaredError(y, t):
    return 0.5*np.sum((y-t)**2)

In [7]:
y = [0.1, 0.05, 0.6, 0.2, 0.05]
t = [0, 0, 1, 0, 0]
meanSquaredError(np.array(y), np.array(t))

0.10750000000000003

In [8]:
y = [0.1, 0.05, 0.05, 0.2, 0.6]
t = [0, 0, 1, 0, 0]
meanSquaredError(np.array(y), np.array(t))

0.6575

## 4.2.2 交差エントロピー誤差

In [4]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t*np.log(y+delta))

In [16]:
t = [0,0,1,0,0,0,0,0,0,0]
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.2, 0.0, 0.0, 0.0,0.0]

In [14]:
t = [0,0,1,0,0,0,0,0,0,0]
y = [[0.1, 0.05, 0.6, 0.0, 0.05, 0.2, 0.0, 0.0, 0.0,0.0],[0.1, 0.05, 0.6, 0.0, 0.05, 0.2, 0.0, 0.0, 0.0,0.0]]

In [9]:
delta = 1e-7
np.array(t)*np.log(np.array(y)+delta)

array([[-0.        , -0.        , -0.51082546, -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ],
       [-0.        , -0.        , -0.51082546, -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ]])

In [17]:
cross_entropy_error(np.array(y), np.array(t))

0.510825457099338

In [18]:
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.2, 0.0, 0.6, 0.0, 0.0]

In [19]:
cross_entropy_error(np.array(y), np.array(t))

2.302584092994546

## 4.2.3ミニバッチ学習

In [1]:
from DLfromscratch.dataset.mnist import load_mnist

In [3]:
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

print(x_train.shape)
print(t_train.shape)

(60000, 784)
(60000, 10)


In [6]:
#10枚ランダムに取り出し
trainSize = x_train.shape[0]
batchSize = 10
batchMask = np.random.choice(trainSize, batchSize)

x_batch = x_train[batchMask]
t_batch = t_train[batchMask]


In [8]:
np.random.choice(trainSize, batchSize)

array([57178, 46628, 58784, 37856, 40311, 30286, 22240, 10450, 24220,
       11460])

## 4.2.4[バッチ対応版]交差エントロピーの実装

In [2]:
#batchの平均値を出力
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    batchSize = y.shape[0]
    delta = 1e-7
    return -np.sum(t*np.log(y+delta))/batchSize

In [3]:
#batchの平均値を出力
#ラベルがone-hotではない場合(2とか７とか)
#引数はnumpy形式であること。
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    batchSize = y.shape[0]
    delta = 1e-7
    #sumは縦横すべて足し合わせる。
    #arrange(5)⇒[0,1,2,3,4]
    return -np.sum(np.log(y[np.arange(batchSize), t]+delta))/batchSize

In [49]:
t = np.array([2,1,0,3,4])
y = np.array([[0,0,1,0,0],[0,0.5,0.5,0,0],[1,0,0,0,0],[0,0,0,1,0],[0,0,0,0,1]])

In [50]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
y[a, t]

array([1. , 0.5, 1. , 1. , 1. ])

In [52]:
delta = 1e-7
-np.sum(np.log(y[a, t]+delta))/5

0.13862931611199703

In [53]:
y = np.array([[0,0,0,1,0],[0,0.5,0.5,0,0],[1,0,0,0,0],[0,0,0,1,0],[0,0,0,0,1]])
delta = 1e-7
-np.sum(np.log(y[a, t]+delta))/5
#明後日の方向の間違いをすると大体O(1)を超えるレベルのスコアが出る。

3.3622484663036607